version: "3"

services:
  backend:
    hostname: backend
    build:
      dockerfile: ./covid_w_polsce/backend/dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default

  frontend:
    build:
      dockerfile: ./covid_w_polsce/frontend/dockerfile
      context: .
    ports:
      - "8501:8501"
    networks:
      - default
    

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports: 
      - 10000:10000 
      - 10001:10001 
      - 10002:10002
    networks:
      - default
    volumes:
      - azurite:/data

networks:
  default:
    driver: bridge

volumes:
  azurite: